Document: mpdas
Title: Debian mpdas Manual
Author: <insert document author here>
Abstract: This manual describes what mpdas is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mpdas/mpdas.sgml.gz

Format: postscript
Files: /usr/share/doc/mpdas/mpdas.ps.gz

Format: text
Files: /usr/share/doc/mpdas/mpdas.text.gz

Format: HTML
Index: /usr/share/doc/mpdas/html/index.html
Files: /usr/share/doc/mpdas/html/*.html
